version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./build_database.sql:/docker-entrypoint-initdb.d/build_database.sql